### ISSUE TITLE
Compounds with strong morphological correlation to PGC1a overexpression are more likely to be hits in a targeted screen for PGC1a activity 

### ISSUE THREAD

**Issue by shntnu** [carpenterlab/2021_Rohban_submitted#6]
(Moved over from https://broadinstitute.atlassian.net/wiki/spaces/IP/pages/607289345/2018-07-13+Test+Are+there+PGC1a+hits+in+common+between+the+Cell+Painting+gene-cpd+hits+and+a+functional+screen)

We have the PGC1a screen [here](https://github.com/broadinstitute/2016_08_22_Gene_Compound/blob/f08ccc2b4763376dd00010bed559f3d531b61dd2/pgc1a/knit_notebooks/1.inspect-pgc1a-screen.md)

We have the gene-compound connections [here](https://github.com/broadinstitute/2016_08_22_Gene_Compound/blob/c004349e81216f4878bc4b73e0ce11bc92990a43/pgc1a/knit_notebooks/2.inspect-gene-compound.md)

The next challenge is to figure out how to get PubChem CID from the Broad ID, because that is what will help us map to the PGC1a screen.

Turns out that is not so simple https://www.biostars.org/p/249949/

More to come

**Comment by mrohban** [comment]
> @AnneCarpenter I'll poke around some more tomorrow. Meanwhile @mrohban if you have the time, it would be great if you can see if I'm reading the right file here to get the gene compound connections. Might not be easy because it's been a while. I'm reasonably certain it's the right file but not 100% sure.
> 
> https://github.com/broadinstitute/2016_08_22_Gene_Compound/blob/5fcdcd8d437a2542aa3a0cfa26926306021d340e/pgc1a/knit_notebooks/2.inspect-gene-compound.md
> 
> (it's called `cr_melt_cp.rds`)

Confirmed.
